### ISSUE TITLE
Morning session peer to peer review

### ISSUE THREAD

**Issue by Elijahdre** [binhussen/leaderboard#4]
### Appraisals 

- Good use of JavaScript ES6 classes.
- Check for the live link in the ReadMe file, it may be broken.

Happy Coding 🥂

**Comment by binhussen** [comment]
Thank you @betses, @techEmprez and @Elijahdre for your feedback, I have updated the changes as requested and made the fixes we discussed [Link here](https://github.com/binhussen/leaderboard/)
